AWSTemplateFormatVersion: '2010-09-09'
Description: Portal & Pluto (MM tools frontend)
Parameters:
  VidispineCluster:
    Type: String
    Description: Vidispine IP address to communicate with
  App:
    Type: String
    Description: Application identifier for RiffRaff
  Stack:
    Type: String
    Description: Stack identifier for RiffRaff
  Stage:
    Type: String
    AllowedValues:
      - CODE
      - PROD
    Description: Deployment stage
  Subnets:
    Description: Subnets within which to deploy
    Type: List<AWS::EC2::Subnet::Id>
  SentryDSN:
    Type: String
    Description: DSN for communicating with Sentry
  KeyPairName:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: Name of an existing key pair, which will be given root access to the instances
Resources:
  PlutoASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
      - eu-west-1a
      - eu-west-1b
      - eu-west-1c
      VPCZoneIdentifier:
        Ref: Subnets
      Cooldown: '500'
      DesiredCapacity: '1'
      HealthCheckGracePeriod: 500
      HealthCheckType: ELB
      LaunchConfigurationName:
        Ref: PlutoLC
      LoadBalancerNames:
      - Ref: PlutoELB
      MaxSize: '4'
      Tags:
        - Key: Name
          Value: Pluto Frontend [autoscaled]
          PropagateAtLaunch: true
        - Key: App
          Value:
            Ref: App
          PropagateAtLaunch: true
        - Key: Stack
          Value:
            Ref: Stack
          PropagateAtLaunch: true
        - Key: Stage
          Value:
            Ref: Stage
          PropagateAtLaunch: true
  PlutoLC:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIPAddress: false
      IamInstanceProfile:
        Fn::GetAtt:
          - PlutoInstanceProfile
          - Arn
      ImageId: "ami-111111"
      InstanceType: "t2.large"
      KeyName:
        Ref: KeyPairName
      UserData:
        Fn::Base64:
          Fn::Join:
            - "\n"
            -
              -"#!/usr/bin/bash"


